const $ = (selector) => document.querySelector(selector);
const portal = location.pathname === "/green" ? "green" : location.pathname === "/red" ? "red" : location.pathname === "/admin" ? "admin" : "combined";
const state = { token: sessionStorage.getItem("sfss_token") || "", cookieSession: false, user: "", globalAdmin: false, projects: [], project: null };
const statusNames = {pending_scan:"待扫描",scanning:"扫描中",quarantined:"已隔离",released:"已放行",rejected:"已拒绝",expired:"已过期"};
const outboundStatusNames = {pending_scan:"待扫描",scanning:"扫描中",quarantined:"已隔离",classified:"已分类",pending_approval:"待审批",approved:"已批准",approval_rejected:"审批拒绝",released_to_green:"已放行至绿区",expired:"已过期"};
const actionNames = {"project.create":"创建项目","project.list":"查看项目列表","membership.add":"添加成员","membership.remove":"移除成员","membership.list":"查看成员","object.upload":"上传文件","object.list":"查看对象列表","object.download":"下载文件","object.read_metadata":"查看元数据","object.state_changed":"状态变化","outbound.list":"查看外发列表","scan.complete":"扫描完成","scan.error":"扫描错误","session.login":"用户登录","session.logout":"用户退出","session.records_purged":"清理失效会话记录","service_token.expired":"服务令牌自动过期","audit.list":"查看审计","admin.config.read":"查看系统配置","admin.session.list":"查看活动会话","admin.session.revoke_user":"撤销用户会话","admin.session.revoke_all":"紧急撤销全部会话","admin.service_identity.create":"创建服务身份","admin.service_identity.update":"更新服务身份","admin.service_token.list":"查看服务令牌","admin.service_token.create":"签发服务令牌","admin.service_token.revoke":"撤销服务令牌","request.denied":"请求拒绝","upload.session.create":"创建分片上传","upload.session.read":"查看上传会话","upload.part.complete":"完成上传分片","upload.session.complete":"完成分片上传","upload.session.cancel":"取消分片上传"};

function toast(message){ const el=$("#toast"); el.textContent=message; el.classList.add("show"); clearTimeout(window.toastTimer); window.toastTimer=setTimeout(()=>el.classList.remove("show"),2600); }
async function api(path, options={}){
  const headers = new Headers(options.headers || {});
  if(state.token) headers.set("Authorization",`Bearer ${state.token}`);
  if(!state.token && !["GET","HEAD"].includes((options.method||"GET").toUpperCase()) && path!=="/v1/auth/login") headers.set("X-SFSS-CSRF","1");
  if(portal==="green"||portal==="red") headers.set("X-SFSS-Zone",portal);
  if(options.json){ headers.set("Content-Type","application/json"); options.body=JSON.stringify(options.json); }
  const response=await fetch(path,{...options,headers,credentials:"same-origin"});
  if(response.status===401){ logout(); throw new Error("登录已失效，请重新登录"); }
  if(!response.ok){ let data={}; try{data=await response.json()}catch{} throw new Error(data.error || `请求失败 (${response.status})`); }
  return response.status===204 ? null : response.json();
}
async function downloadFile(path,record,zone){
  const headers={"X-SFSS-Zone":zone};if(state.token)headers.Authorization=`Bearer ${state.token}`;
  let handle=null;
  if("showSaveFilePicker" in window){
    handle=await window.showSaveFilePicker({suggestedName:record.filename});
  }else if(record.size>256*1024*1024){
    throw new Error("当前浏览器不支持大文件流式保存，请使用 sfss-agent 断点续传下载");
  }
  const response=await fetch(path,{headers});
  if(response.status===401){logout();throw new Error("登录已失效，请重新登录");}
  if(!response.ok){let data={};try{data=await response.json()}catch{}throw new Error(data.error||"下载失败");}
  if(!handle){
    const blob=await response.blob();const url=URL.createObjectURL(blob);const a=document.createElement("a");
    a.href=url;a.download=record.filename;document.body.append(a);a.click();a.remove();URL.revokeObjectURL(url);return;
  }
  if(!response.body)throw new Error("浏览器没有提供下载数据流");
  const writable=await handle.createWritable({keepExistingData:false});let received=0;
  try{
    const reader=response.body.getReader();
    while(true){const {done,value}=await reader.read();if(done)break;await writable.write(value);received+=value.byteLength;}
    if(received!==record.size)throw new Error(`下载不完整：预期 ${record.size} 字节，实际 ${received} 字节`);
    await writable.close();
  }catch(err){try{await writable.abort();}catch{}throw err;}
}
function showLogin(){ $("#login-view").hidden=false; $("#app-view").hidden=true; }
function showApp(){ $("#login-view").hidden=true; $("#app-view").hidden=false; $("#current-user").textContent=state.user; $("#admin-console").hidden=portal!=="combined"||!state.globalAdmin; }
function logout(){ state.token=""; state.cookieSession=false; state.user=""; state.project=null; sessionStorage.removeItem("sfss_token"); showLogin(); }
async function performLogout(){try{await api("/v1/auth/logout",{method:"POST"});}catch{}finally{logout();}}

function applyPortalLayout(){
  if(portal==="green"){
    document.title="SFSS 绿区文件门户"; $("#portal-login-title").textContent="登录绿区文件门户";
    $("#new-project").hidden=true; $("#admin-console").hidden=true;
    $("#files-tab-button").textContent="文件上传"; $("#outbound-tab-button").textContent="审批通过文件";
    $("#outbound-policy-form").hidden=true; $("#outbound-upload-form").hidden=true;
    document.querySelector('[data-tab="members"]').hidden=true; document.querySelector('[data-tab="audit"]').hidden=true;
    $("#object-table-title").textContent="我的上传状态";
  }else if(portal==="red"){
    document.title="SFSS 红区文件门户"; $("#portal-login-title").textContent="登录红区文件门户";
    $("#new-project").hidden=true; $("#admin-console").hidden=true; $("#upload-form").hidden=true;
    $("#files-tab-button").textContent="绿区放行缓冲区"; $("#object-table-title").textContent="可下载文件";
    $("#outbound-tab-button").textContent="文件外发"; $("#outbound-policy-form").hidden=true;
    document.querySelector('[data-tab="members"]').hidden=true; document.querySelector('[data-tab="audit"]').hidden=true;
  }else if(portal==="admin"){
    document.title="SFSS 管理后台"; $("#portal-login-title").textContent="登录管理员后台";
  }
}
applyPortalLayout();

$("#login-form").addEventListener("submit",async event=>{
  event.preventDefault(); const error=$("#login-error"); error.hidden=true;
  try{ const result=await api("/v1/auth/login",{method:"POST",json:{username:$("#username").value,password:$("#password").value}}); state.token=result.token||"";state.cookieSession=result.session_transport==="cookie";if(state.token)sessionStorage.setItem("sfss_token",state.token);else sessionStorage.removeItem("sfss_token"); const me=await api("/v1/me");state.user=me.username;state.globalAdmin=me.global_admin;showApp(); await loadHealth(); await loadProjects(); if(location.pathname==="/admin"&&state.globalAdmin)await openAdmin(); }
  catch(err){ error.textContent=err.message; error.hidden=false; }
});
$("#logout").addEventListener("click",performLogout);

async function loadHealth(){ try{const health=await api("/health"); $("#scanner-state").textContent=health.status==="ok"?"服务在线":"服务异常";}catch{} }
async function loadProjects(selectId, stayAdmin=false){
  const data=await api("/v1/projects"); state.projects=data.projects; const list=$("#project-list"); list.replaceChildren();
  data.projects.forEach(project=>{const button=document.createElement("button");button.className="project-item"+(state.project?.id===project.id?" active":"");button.textContent=project.name;button.title=project.id;button.onclick=()=>selectProject(project);list.append(button);});
  if(stayAdmin)return;
  const selected=data.projects.find(p=>p.id===(selectId||state.project?.id)); if(selected) await selectProject(selected); else if(data.projects.length) await selectProject(data.projects[0]); else{$("#empty-state").hidden=false;$("#project-view").hidden=true;}
}
function activateProjectTab(name){document.querySelectorAll(".tab").forEach(button=>button.classList.toggle("active",button.dataset.tab===name));document.querySelectorAll(".tab-panel").forEach(panel=>panel.hidden=panel.id!==`tab-${name}`);}
async function selectProject(project){
  state.project=project; $("#empty-state").hidden=true; $("#admin-view").hidden=true; $("#project-view").hidden=false; $("#project-title").textContent=project.name; $("#project-meta").textContent=`${project.id} · 权限：${[...project.roles,...project.outbound_roles].join(", ") || "仅平台管理"}`; document.querySelectorAll(".project-item").forEach(b=>b.classList.toggle("active",b.title===project.id));
  if(portal==="green"){
    const canUpload=project.roles.some(role=>role==="admin"||role==="uploader");const canDownload=project.outbound_roles.includes("green_downloader");$("#files-tab-button").hidden=!canUpload;$("#outbound-tab-button").hidden=!canDownload;$("#upload-form").hidden=!canUpload;
    if(!canUpload&&canDownload){activateProjectTab("outbound");await loadOutbound();return;}
  }else if(portal==="red"){
    const canBuffer=project.roles.some(role=>role==="admin"||role==="downloader");const canOutbound=project.outbound_roles.some(role=>role==="red_uploader"||role==="approver");$("#files-tab-button").hidden=!canBuffer;$("#outbound-tab-button").hidden=!canOutbound;$("#outbound-upload-form").hidden=!project.outbound_roles.includes("red_uploader");
    if(!canBuffer&&canOutbound){activateProjectTab("outbound");await loadOutbound();return;}
  }
  activateProjectTab("files");await loadObjects();
}

async function openAdmin(){$("#empty-state").hidden=true;$("#project-view").hidden=true;$("#admin-view").hidden=false;document.querySelectorAll(".project-item").forEach(b=>b.classList.remove("active"));await loadAdmin();}
$("#admin-console").onclick=openAdmin;
$("#admin-refresh").onclick=async()=>{await loadAdmin();toast("管理员总览已刷新");};
document.querySelectorAll(".admin-tab").forEach(button=>button.onclick=()=>{document.querySelectorAll(".admin-tab").forEach(tab=>tab.classList.toggle("active",tab===button));document.querySelectorAll(".admin-page").forEach(page=>page.hidden=page.id!==`admin-page-${button.dataset.adminPage}`);});
async function loadAdmin(){
  try{const [data,config,serviceTokens,humanSessions]=await Promise.all([api("/v1/admin/overview"),api("/v1/admin/config"),api("/v1/admin/service-tokens"),api("/v1/admin/sessions")]);$("#metric-users").textContent=data.counts.users;$("#metric-projects").textContent=data.counts.projects;$("#metric-objects").textContent=data.counts.objects;$("#metric-bytes").textContent=formatSize(data.counts.bytes);$("#metric-storage-available").textContent=formatSize(data.storage?.available_bytes||0);$("#metric-active-uploads").textContent=data.counts.active_uploads||0;$("#metric-staged-bytes").textContent=formatSize(data.counts.staged_bytes||0);$("#metric-scan-jobs").textContent=(data.queue?.queued||0)+(data.queue?.running||0);$("#metric-audit-chain").textContent=`已验证 ${data.audit_chain?.events||0} 条`;
    $("#config-retention").value=config.retention_hours;$("#config-upload").value=config.max_upload_mb;$("#config-chunk").value=config.multipart_chunk_mb;$("#config-upload-session").value=config.upload_session_hours;$("#config-active-uploads").value=config.max_active_uploads_per_user;$("#config-staged-gb").value=config.max_staged_gb_per_project;$("#config-min-free-gb").value=config.min_free_gb;$("#config-scanners").value=config.scanners;$("#config-clam-host").value=config.clamav_host;$("#config-clam-port").value=config.clamav_port;$("#config-clam-stream").value=config.clamav_stream_max_mb;$("#config-yara").value=config.yara_rules;$("#service-token-hours").max=config.service_token_max_hours;if(Number($("#service-token-hours").value)>config.service_token_max_hours)$("#service-token-hours").value=config.service_token_max_hours;
    const summary=$("#state-summary");summary.replaceChildren();Object.entries(statusNames).forEach(([key,label])=>{const item=document.createElement("div");item.className="state-item";const name=document.createElement("span");name.textContent=`入站 · ${label}`;const count=document.createElement("strong");count.textContent=data.states[key]||0;item.append(name,count);summary.append(item);});Object.entries(outboundStatusNames).forEach(([key,label])=>{const countValue=data.outbound_states?.[key]||0;if(!countValue)return;const item=document.createElement("div");item.className="state-item";const name=document.createElement("span");name.textContent=`外发 · ${label}`;const count=document.createElement("strong");count.textContent=countValue;item.append(name,count);summary.append(item);});
    const users=$("#admin-user-rows");users.replaceChildren();data.users.forEach(user=>{const tr=document.createElement("tr");const actions=document.createElement("td");if(user.principal_type==="service"){actions.append(actionButton(user.enabled?"停用":"启用",()=>updateServiceIdentity(user.username,!user.enabled),user.enabled));}else{actions.append(actionButton("重置密码",()=>resetUserPassword(user.username)));if(user.username!==state.user){actions.append(actionButton(user.enabled?"停用":"启用",()=>updateUser(user.username,{enabled:!user.enabled}),user.enabled));actions.append(actionButton(user.global_admin?"取消平台管理":"设为平台管理",()=>updateUser(user.username,{global_admin:!user.global_admin})));}}tr.append(cell(user.username),cell(user.principal_type==="service"?"服务身份":user.global_admin?"平台管理员":"普通用户"),cell(user.enabled?"启用":"停用",user.enabled?"status-enabled":"status-disabled"),cell(String(user.project_count)),cell(user.roles||"—"),actions);users.append(tr);});
    const tokenRows=$("#service-token-rows");tokenRows.replaceChildren();serviceTokens.tokens.forEach(token=>{const tr=document.createElement("tr");const status=token.revoked?"已撤销":token.expires_at<=Date.now()/1000?"已过期":"有效";const actions=document.createElement("td");if(!token.revoked&&token.expires_at>Date.now()/1000)actions.append(actionButton("撤销",()=>revokeServiceToken(token),true));else actions.textContent="—";tr.append(cell(token.label),cell(token.username),cell(token.project_id),cell(`${token.zone} · ${token.permissions.join(", ")}`),cell(new Date(token.expires_at*1000).toLocaleString()),cell(token.last_used_at?new Date(token.last_used_at*1000).toLocaleString():"从未"),cell(status,status==="有效"?"status-enabled":"status-disabled"),actions);tokenRows.append(tr);});
    $("#session-policy-summary").textContent=`绝对 ${Math.floor(humanSessions.absolute_ttl_seconds/60)} 分钟 · 空闲 ${Math.floor(humanSessions.idle_ttl_seconds/60)} 分钟 · 每用户最多 ${humanSessions.max_per_user} 个`;
    const sessionRows=$("#admin-session-rows");sessionRows.replaceChildren();humanSessions.sessions.forEach(session=>{const tr=document.createElement("tr");const actions=document.createElement("td");actions.append(actionButton("撤销该用户全部会话",()=>revokeUserSessions(session.username),true));tr.append(cell(session.username),cell(session.auth_backend),cell(session.zone),cell(new Date(session.created_at*1000).toLocaleString()),cell(new Date(session.last_seen_at*1000).toLocaleString()),cell(new Date(session.expires_at*1000).toLocaleString()),actions);sessionRows.append(tr);});
    const projects=$("#admin-project-rows");projects.replaceChildren();data.projects.forEach(project=>{const tr=document.createElement("tr");const actions=document.createElement("td");if(!project.archived){actions.append(actionButton("改名",()=>renameProject(project)));actions.append(actionButton("归档",()=>archiveProject(project),true));}else actions.append(actionButton("恢复项目",()=>restoreProject(project)));tr.append(cell(project.name),cell(project.id),cell(String(project.member_count)),cell(String(project.object_count)),cell(formatSize(project.total_bytes)),cell(new Date(project.created_at*1000).toLocaleString()),actions);projects.append(tr);});
    const objects=$("#admin-object-rows");objects.replaceChildren();const managedObjects=[...data.objects.map(item=>({...item,direction:"objects"})),...(data.outbound_objects||[]).map(item=>({...item,direction:"outbound"}))];managedObjects.forEach(object=>{const tr=document.createElement("tr");const status=document.createElement("td");const badge=document.createElement("span");badge.className=`badge ${object.state}`;badge.textContent=(object.direction==="outbound"?outboundStatusNames:statusNames)[object.state]||object.state;status.append(badge);const actions=document.createElement("td");if(object.state==="quarantined")actions.append(actionButton("重新扫描",()=>objectAction(object,"rescan")));const expirable=object.direction==="outbound"?["pending_scan","quarantined","pending_approval","approval_rejected","released_to_green"]:["released","quarantined","rejected"];if(expirable.includes(object.state))actions.append(actionButton("立即过期",()=>objectAction(object,"expire"),true));if(!actions.childNodes.length)actions.textContent="—";tr.append(cell(object.filename),cell(object.project_id),cell(`${object.direction==="outbound"?"外发":"入站"} · ${object.media_type}`),status,cell(formatSize(object.size)),actions);objects.append(tr);});
    const approvals=$("#admin-approval-rows");approvals.replaceChildren();(data.pending_approvals||[]).forEach(transfer=>{const tr=document.createElement("tr");const actions=document.createElement("td");actions.append(actionButton("批准",()=>adminDecideOutbound(transfer,true)));actions.append(actionButton("拒绝",()=>adminDecideOutbound(transfer,false),true));tr.append(cell(transfer.filename),cell(transfer.project_id),cell(transfer.classification||"—"),cell(transfer.uploader),cell(transfer.approval_expires_at?new Date(transfer.approval_expires_at*1000).toLocaleString():"—"),actions);approvals.append(tr);});
    const events=$("#admin-event-rows");events.replaceChildren();data.events.forEach(event=>{const tr=document.createElement("tr");tr.append(cell(new Date(event.timestamp*1000).toLocaleString()),cell(event.actor),cell(actionNames[event.action]||event.action),cell(event.outcome),cell(event.project_id||"—"),cell(event.source_zone));events.append(tr);});
  }catch(err){toast(err.message);}
}
function actionButton(label,handler,danger=false){const button=document.createElement("button");button.type="button";button.className=`secondary small-action${danger?" danger":""}`;button.textContent=label;button.onclick=handler;return button;}
$("#security-config-form").addEventListener("submit",async event=>{event.preventDefault();try{const result=await api("/v1/admin/config",{method:"PUT",json:{retention_hours:Number($("#config-retention").value),max_upload_mb:Number($("#config-upload").value),multipart_chunk_mb:Number($("#config-chunk").value),upload_session_hours:Number($("#config-upload-session").value),max_active_uploads_per_user:Number($("#config-active-uploads").value),max_staged_gb_per_project:Number($("#config-staged-gb").value),min_free_gb:Number($("#config-min-free-gb").value),scanners:$("#config-scanners").value,clamav_host:$("#config-clam-host").value,clamav_port:Number($("#config-clam-port").value),yara_rules:$("#config-yara").value}});toast(result.restart_required?"生产配置已暂存：数据面已关闭，请完成变更审批、指纹、预检和重启":"安全与传输配置已保存并生效");await loadAdmin();}catch(err){toast(err.message);}});
$("#admin-user-form").addEventListener("submit",async event=>{event.preventDefault();try{await api("/v1/admin/users",{method:"POST",json:{username:$("#admin-new-user").value,password:$("#admin-new-password").value,global_admin:$("#admin-new-global").checked}});event.target.reset();toast("本地账号已创建");await loadAdmin();}catch(err){toast(err.message);}});
$("#service-identity-form").addEventListener("submit",async event=>{event.preventDefault();try{await api("/v1/admin/service-identities",{method:"POST",json:{username:$("#service-identity-user").value}});event.target.reset();toast("非交互服务身份已创建，请继续分配项目角色");await loadAdmin();}catch(err){toast(err.message);}});
async function updateServiceIdentity(username,enabled){try{await api(`/v1/admin/service-identities/${encodeURIComponent(username)}`,{method:"PUT",json:{enabled}});toast("服务身份状态已更新");await loadAdmin();}catch(err){toast(err.message);}}
$("#service-token-form").addEventListener("submit",async event=>{event.preventDefault();const permissions=[...document.querySelectorAll(".service-token-permission:checked")].map(input=>input.value);try{const result=await api("/v1/admin/service-tokens",{method:"POST",json:{label:$("#service-token-label").value,username:$("#service-token-user").value,project_id:$("#service-token-project").value,zone:$("#service-token-zone").value,permissions,expires_hours:Number($("#service-token-hours").value)}});window.prompt("服务令牌仅显示一次，请立即复制到目标区域的秘密管理器：",result.token);event.target.reset();$("#service-token-hours").value=$("#service-token-hours").max;toast("服务令牌已签发");await loadAdmin();}catch(err){toast(err.message);}});
async function revokeServiceToken(token){if(!window.confirm(`撤销服务令牌“${token.label}”？`))return;try{await api(`/v1/admin/service-tokens/${token.id}`,{method:"DELETE"});toast("服务令牌已撤销");await loadAdmin();}catch(err){toast(err.message);}}
async function resetUserPassword(username){const password=window.prompt(`为 ${username} 设置新密码（至少 8 位）`);if(!password)return;try{await api(`/v1/admin/users/${encodeURIComponent(username)}`,{method:"PUT",json:{password}});toast("密码已重置");}catch(err){toast(err.message);}}
async function updateUser(username,changes){try{await api(`/v1/admin/users/${encodeURIComponent(username)}`,{method:"PUT",json:changes});toast("账号配置已更新");await loadAdmin();}catch(err){toast(err.message);}}
async function revokeUserSessions(username){if(!window.confirm(`撤销 ${username} 的全部人工会话？该用户必须重新登录。`))return;try{await api(`/v1/admin/users/${encodeURIComponent(username)}/revoke-sessions`,{method:"POST",json:{confirmation:username}});if(username===state.user){sessionStorage.removeItem("sfss_token");state.token="";showLogin();return;}toast("该用户的人工会话已全部撤销");await loadAdmin();}catch(err){toast(err.message);}}
$("#revoke-all-sessions").onclick=async()=>{const phrase=window.prompt("紧急操作会让所有人员立即重新登录。请输入：REVOKE ALL HUMAN SESSIONS");if(phrase!=="REVOKE ALL HUMAN SESSIONS")return;try{await api("/v1/admin/sessions/revoke-all",{method:"POST",json:{confirmation:phrase}});sessionStorage.removeItem("sfss_token");state.token="";showLogin();}catch(err){toast(err.message);}};
async function renameProject(project){const name=window.prompt("新的项目名称",project.name);if(!name||name===project.name)return;try{await api(`/v1/admin/projects/${encodeURIComponent(project.id)}`,{method:"PUT",json:{name}});toast("项目名称已更新");await loadAdmin();await loadProjects(null,true);}catch(err){toast(err.message);}}
async function archiveProject(project){if(!window.confirm(`归档项目“${project.name}”？归档后项目文件将不可访问。`))return;try{await api(`/v1/admin/projects/${encodeURIComponent(project.id)}`,{method:"DELETE"});toast("项目已归档");await loadAdmin();await loadProjects(null,true);}catch(err){toast(err.message);}}
async function restoreProject(project){try{await api(`/v1/admin/projects/${encodeURIComponent(project.id)}/restore`,{method:"POST"});toast("项目已恢复");await loadAdmin();await loadProjects(null,true);}catch(err){toast(err.message);}}
async function objectAction(object,action){if(action==="expire"&&!window.confirm(`让文件“${object.filename}”立即过期？`))return;try{await api(`/v1/admin/${object.direction||"objects"}/${object.id}/${action}`,{method:"POST"});toast(action==="rescan"?"重新扫描已提交":"对象已过期");await loadAdmin();}catch(err){toast(err.message);}}
async function adminDecideOutbound(transfer,approved){const comment=window.prompt(approved?"管理平面审批意见":"拒绝原因",approved?"同意外发":"不符合外发策略");if(comment===null)return;try{await api(`/v1/projects/${encodeURIComponent(transfer.project_id)}/outbound/${transfer.id}/decision`,{method:"POST",json:{approved,comment}});toast(approved?"外发已批准":"外发已拒绝");await loadAdmin();}catch(err){toast(err.message);}}

$("#new-project").onclick=()=>$("#project-dialog").showModal();
$("#close-dialog").onclick=()=>$("#project-dialog").close();
$("#project-form").addEventListener("submit",async event=>{event.preventDefault();try{const project=await api("/v1/projects",{method:"POST",json:{id:$("#project-id").value,name:$("#project-name").value}});$("#project-dialog").close();event.target.reset();toast("项目已创建");await loadProjects(project.id);}catch(err){toast(err.message);}});

async function sha256Hex(blob){const bytes=await blob.arrayBuffer();const digest=await crypto.subtle.digest("SHA-256",bytes);return [...new Uint8Array(digest)].map(value=>value.toString(16).padStart(2,"0")).join("");}
async function multipartUpload(file,direction,progress){
  const projectId=state.project.id;const key=`sfss-upload:${direction}:${projectId}:${file.name}:${file.size}:${file.lastModified}`;const zoneHeaders={"X-SFSS-Zone":direction==="inbound"?"green":"red"};let session;
  const saved=localStorage.getItem(key);
  if(saved){try{session=await api(`/v1/uploads/${saved}`,{headers:zoneHeaders});if(session.state!=="uploading")throw new Error("closed");}catch{localStorage.removeItem(key);session=null;}}
  if(!session){session=await api(`/v1/projects/${encodeURIComponent(projectId)}/uploads`,{method:"POST",headers:zoneHeaders,json:{direction,filename:file.name,total_size:file.size}});localStorage.setItem(key,session.id);}
  const completed=new Set((session.parts||[]).map(part=>part.part_number));let next=1;let uploaded=session.received_bytes||0;progress(uploaded,file.size);
  async function worker(){while(true){const number=next++;if(number>session.part_count)return;if(completed.has(number))continue;const start=(number-1)*session.chunk_size;const part=file.slice(start,Math.min(file.size,start+session.chunk_size));const hash=await sha256Hex(part);await api(`/v1/uploads/${session.id}/parts/${number}`,{method:"PUT",body:part,headers:{...zoneHeaders,"Content-Type":"application/octet-stream","X-Part-SHA256":hash}});uploaded+=part.size;progress(uploaded,file.size);}}
  await Promise.all(Array.from({length:Math.min(4,session.part_count)},()=>worker()));
  const record=await api(`/v1/uploads/${session.id}/complete`,{method:"POST",headers:zoneHeaders});localStorage.removeItem(key);return record;
}
function uploadProgress(button,prefix){return(done,total)=>{const percent=Math.floor(done*100/total);button.textContent=`${prefix} ${percent}%`;};}
$("#upload-form").addEventListener("submit",async event=>{event.preventDefault();const file=$("#file-input").files[0];if(!file||!state.project)return;const button=event.submitter||event.target.querySelector("button");button.disabled=true;try{toast("正在分片上传至隔离区…");await multipartUpload(file,"inbound",uploadProgress(button,"上传中"));event.target.reset();toast("上传完成，扫描任务已提交");await loadObjects();}catch(err){toast(`${err.message}，可重新选择同一文件继续`);}finally{button.disabled=false;button.textContent="上传并扫描";}});

async function loadOutbound(){if(!state.project)return;const isAdmin=state.project.roles.includes("admin");const canConfigure=isAdmin&&(portal==="combined"||portal==="admin");$("#outbound-policy-form").hidden=!canConfigure;try{if(canConfigure){const policy=await api(`/v1/projects/${encodeURIComponent(state.project.id)}/outbound-policy`);$("#outbound-enabled").checked=Boolean(policy.enabled);const localOption=$("#outbound-provider").querySelector('option[value="local"]');localOption.disabled=!policy.local_approval_allowed;$("#outbound-provider").value=policy.approval_provider;$("#outbound-approval-hours").value=policy.approval_timeout_hours;$("#outbound-download-hours").value=policy.download_ttl_hours;document.querySelectorAll(".outbound-class").forEach(input=>input.checked=policy.allowed_classifications.includes(input.value));}
  const data=await api(`/v1/projects/${encodeURIComponent(state.project.id)}/outbound`);const rows=$("#outbound-rows");rows.replaceChildren();data.transfers.filter(transfer=>portal!=="green"||transfer.state==="released_to_green").forEach(transfer=>{const tr=document.createElement("tr");const file=document.createElement("td");file.className="file-cell";const strong=document.createElement("strong");strong.textContent=transfer.filename;const small=document.createElement("small");small.textContent=transfer.sha256.slice(0,12)+"…";file.append(strong,small);const status=document.createElement("td");const badge=document.createElement("span");badge.className=`badge ${transfer.state}`;badge.textContent=outboundStatusNames[transfer.state]||transfer.state;status.append(badge);const actions=document.createElement("td");if((portal==="combined"||portal==="admin")&&transfer.state==="pending_approval"&&state.project.outbound_roles.includes("approver")){actions.append(actionButton("批准",()=>decideOutbound(transfer,true)));actions.append(actionButton("拒绝",()=>decideOutbound(transfer,false),true));}if(portal!=="red"&&transfer.state==="released_to_green"&&state.project.outbound_roles.includes("green_downloader"))actions.append(actionButton("绿区下载",()=>downloadOutbound(transfer)));if(!actions.childNodes.length)actions.textContent="—";const expiry=transfer.download_expires_at||transfer.approval_expires_at;tr.append(file,cell(transfer.classification||"—"),status,cell(transfer.uploader),cell(transfer.approval_actor||"—"),cell(expiry?new Date(expiry*1000).toLocaleString():"—"),actions);rows.append(tr);});
}catch(err){toast(err.message);}}
$("#outbound-policy-form").addEventListener("submit",async event=>{event.preventDefault();const allowed=[...document.querySelectorAll(".outbound-class:checked")].map(input=>input.value);try{await api(`/v1/projects/${encodeURIComponent(state.project.id)}/outbound-policy`,{method:"PUT",json:{enabled:$("#outbound-enabled").checked,approval_provider:$("#outbound-provider").value,approval_timeout_hours:Number($("#outbound-approval-hours").value),download_ttl_hours:Number($("#outbound-download-hours").value),allowed_classifications:allowed}});toast("外发策略已保存");await loadOutbound();}catch(err){toast(err.message);}});
$("#outbound-upload-form").addEventListener("submit",async event=>{event.preventDefault();const file=$("#outbound-file").files[0];if(!file)return;const button=event.submitter||event.target.querySelector("button");button.disabled=true;try{toast("正在从红区分片上传…");await multipartUpload(file,"outbound",uploadProgress(button,"上传中"));event.target.reset();toast("外发申请已提交");await loadOutbound();}catch(err){toast(`${err.message}，可重新选择同一文件继续`);}finally{button.disabled=false;button.textContent="上传并发起审批";}});
async function decideOutbound(transfer,approved){const comment=window.prompt(approved?"审批意见（批准）":"拒绝原因",approved?"同意外发":"不符合外发策略");if(comment===null)return;try{await api(`/v1/projects/${encodeURIComponent(state.project.id)}/outbound/${transfer.id}/decision`,{method:"POST",json:{approved,comment}});toast(approved?"已批准并放行至绿区":"已拒绝外发");await loadOutbound();}catch(err){toast(err.message);}}
async function downloadOutbound(transfer){try{await downloadFile(`/v1/projects/${encodeURIComponent(state.project.id)}/outbound/${transfer.id}/download`,transfer,"green");toast("绿区下载完成");}catch(err){if(err.name!=="AbortError")toast(err.message);}}
$("#outbound-refresh").onclick=loadOutbound;

function formatSize(bytes){if(bytes<1024)return `${bytes} B`;if(bytes<1048576)return `${(bytes/1024).toFixed(1)} KB`;return `${(bytes/1048576).toFixed(1)} MB`;}
function cell(text,className){const td=document.createElement("td");td.textContent=text;if(className)td.className=className;return td;}
async function loadObjects(){ if(!state.project)return; try{const data=await api(`/v1/projects/${encodeURIComponent(state.project.id)}/objects`);const visible=data.objects.filter(obj=>portal!=="red"||obj.state==="released");$("#object-count").textContent=`${visible.length} 个对象`;const rows=$("#object-rows");rows.replaceChildren();visible.forEach(obj=>{const tr=document.createElement("tr");const fileTd=document.createElement("td");fileTd.className="file-cell";const strong=document.createElement("strong");strong.textContent=obj.filename;const small=document.createElement("small");small.textContent=new Date(obj.created_at*1000).toLocaleString();fileTd.append(strong,small);tr.append(fileTd,cell(obj.media_type),cell(obj.sha256.slice(0,12)+"…","hash"));const statusTd=document.createElement("td");const badge=document.createElement("span");badge.className=`badge ${obj.state}`;badge.textContent=statusNames[obj.state]||obj.state;statusTd.append(badge);tr.append(statusTd,cell(formatSize(obj.size)));const action=document.createElement("td");if(portal!=="green"&&obj.state==="released"){const button=document.createElement("button");button.className="secondary download";button.textContent="红区下载";button.onclick=()=>downloadObject(obj);action.append(button);}else action.textContent="—";tr.append(action);rows.append(tr);});}catch(err){toast(err.message);} }
async function downloadObject(obj){try{await downloadFile(`/v1/projects/${encodeURIComponent(state.project.id)}/objects/${obj.id}/download`,obj,"red");toast("红区下载完成");}catch(err){if(err.name!=="AbortError")toast(err.message);}}

$("#member-form").addEventListener("submit",async event=>{event.preventDefault();try{await api(`/v1/projects/${encodeURIComponent(state.project.id)}/members`,{method:"POST",json:{username:$("#member-user").value,role:$("#member-role").value}});event.target.reset();toast("成员权限已添加");await loadMembers();}catch(err){toast(err.message);}});
const roleNames={admin:"项目管理员",uploader:"绿区上传者",downloader:"红区下载者",auditor:"审计员",red_uploader:"红区外发上传者",approver:"外发审批人",green_downloader:"绿区外发下载者"};
async function loadMembers(){if(!state.project)return;const isAdmin=state.project.roles.includes("admin");$("#network-policy-form").hidden=!isAdmin;try{const data=await api(`/v1/projects/${encodeURIComponent(state.project.id)}/members`);const rows=$("#member-rows");rows.replaceChildren();data.members.forEach(member=>{const tr=document.createElement("tr");const actions=document.createElement("td");actions.append(actionButton("撤销角色",()=>removeMember(member),true));tr.append(cell(member.username),cell(roleNames[member.role]||member.role),actions);rows.append(tr);});if(isAdmin){const policy=await api(`/v1/projects/${encodeURIComponent(state.project.id)}/network-policy`);$("#inbound-cidrs").value=policy.inbound_upload_cidrs.join("\n");$("#outbound-cidrs").value=policy.outbound_upload_cidrs.join("\n");}}catch(err){toast(err.message);}}
async function removeMember(member){if(!window.confirm(`撤销 ${member.username} 的${roleNames[member.role]||member.role}角色？`))return;try{await api(`/v1/projects/${encodeURIComponent(state.project.id)}/members/${encodeURIComponent(member.username)}/${member.role}`,{method:"DELETE"});toast("成员角色已撤销");await loadMembers();}catch(err){toast(err.message);}}
$("#members-refresh").onclick=loadMembers;
function cidrLines(selector){return $(selector).value.split(/[\n,]/).map(value=>value.trim()).filter(Boolean);}
$("#network-policy-form").addEventListener("submit",async event=>{event.preventDefault();try{await api(`/v1/projects/${encodeURIComponent(state.project.id)}/network-policy`,{method:"PUT",json:{inbound_upload_cidrs:cidrLines("#inbound-cidrs"),outbound_upload_cidrs:cidrLines("#outbound-cidrs")}});toast("上传来源 IP 策略已保存");await loadMembers();}catch(err){toast(err.message);}});
async function loadAudit(){if(!state.project)return;try{const data=await api(`/v1/projects/${encodeURIComponent(state.project.id)}/audit`);const rows=$("#audit-rows");rows.replaceChildren();data.events.forEach(item=>{const tr=document.createElement("tr");tr.append(cell(new Date(item.timestamp*1000).toLocaleString()),cell(item.actor),cell(actionNames[item.action]||item.action),cell(item.outcome),cell(item.source_zone),cell(item.object_id?item.object_id.slice(0,8):"—"));rows.append(tr);});}catch(err){toast(err.message);}}
document.querySelectorAll(".tab").forEach(button=>button.onclick=async()=>{document.querySelectorAll(".tab").forEach(b=>b.classList.toggle("active",b===button));document.querySelectorAll(".tab-panel").forEach(panel=>panel.hidden=panel.id!==`tab-${button.dataset.tab}`);if(button.dataset.tab==="audit")await loadAudit();if(button.dataset.tab==="members")await loadMembers();if(button.dataset.tab==="outbound")await loadOutbound();});
$("#refresh").onclick=async()=>{await loadObjects();toast("状态已刷新");};

(async()=>{try{const me=await api("/v1/me");state.cookieSession=!state.token;state.user=me.username;state.globalAdmin=me.global_admin;showApp();await loadHealth();await loadProjects();if(location.pathname==="/admin"&&state.globalAdmin)await openAdmin();}catch{showLogin();}})();
